spring:
  datasource:
    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_POTS:5432}/${APP_DB_NAME:meetfriends}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show-sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true
jwt:
  secret: v3QIv4OqTx+0NStLvJzQfGp8VbD1F5m5Rg4fGYO1oFgKg6Rs2fzjShFyF+YZWbbBjo6Zo3Hgx8+KzH6q4s4NZw==




frontend:
  url: ${FRONTEND_API_URL:http://localhost:4200}